services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_load_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
