version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_server
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
